version: '3.9'

name: ahleen
services:
  account:
    build:
      context: ./account
      dockerfile: Dockerfile
      target: final
    ports: [ "18081:18081" ]
    restart: on-failure
    depends_on:
      - rabbitmq
    command: dotnet account.dll
  statement:
    build:
      context: ./statement
      dockerfile: Dockerfile
      target: final
    ports: [ "18083:18083" ]
    restart: on-failure
    depends_on:
      - rabbitmq
    command: dotnet statement.dll
  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
      target: final
    depends_on:
      - rabbitmq
    ports: [ "18082:18082" ]
    restart: on-failure
    command: dotnet payment.dll
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    # volumes:
    #   - mongodb_data:/data/db
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
            - '5672:5672'
            - '15672:15672'
    # volumes:
    #     - rabbitmq_data:/var/lib/rabbitmq/
    #     - rabbitmq_data:/var/log/rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data:
  rabbitmq_log:


