version: '3.9'

name: ahleen
services:
  account:
    build:
      context: ./account
      dockerfile: Dockerfile
      target: final
    ports: [ "18081:18081" ]
    restart: on-failure
    depends_on:
      - rabbitmq
    # command: tail -f /dev/null
    command: dotnet account.dll
  statement:
    build:
      context: ./statement
      dockerfile: Dockerfile
      target: final
    ports: [ "18083:18083" ]
    restart: on-failure
    depends_on:
      - rabbitmq
    # command: tail -f /dev/null
    command: dotnet statement.dll
  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
      target: final
    depends_on:
      - rabbitmq
    ports: [ "18082:18082" ]
    restart: on-failure
    # command: tail -f /dev/null
    command: dotnet payment.dll
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
            - '5672:5672'
            - '15672:15672'
    # volumes:
    #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq



