version: '3.9'

name: ahleen
services:
  account:
    build:
      context: ./account
      dockerfile: Dockerfile
      target: final
    ports: [ "18081:18081" ]
    # command: tail -f /dev/null
    command: dotnet account.dll

